name: Karate API Tests

on:
  push:
    branches: [ "main" ]

jobs:
  karate-test:
    runs-on: ubuntu-latest

    env:
      BASE_URL: http://mpay-uat.okdollar.org

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Debug files (VERY IMPORTANT)
        run: ls -R

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Run Karate Tests
        run: mvn clean test

      - name: Upload Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: karate-html-report
          path: target/karate-reports/